database:
  debug: 0
  url: mysql+pymysql://username:password@host:port/dbname?charset=utf8mb4

google_api_key: A5za4yB5_iFazO4zAaVGg966mcS2-75Ao2CU3NA

admin_line: Uda4a29f7c0114569af132d046d92f81b
line_bot:
  admin: V2sk/AKiRq8b1fNhHN/6vTBeS2211S/Bv6BPjmEWLo42YX85dUNNf9Zo+7I2iTxB4CwfisJwIggWxowkm5Pr88Z0ddUIBHnTse73lByF5myH8OSdaHi6yn8bX2L7k960X1xtSh+7C9Fpo4c5P4rmgwdB04t89/1O/w1cDnyilFU=
  None: +9FIMMNc30F2Roa6OZIR5Vf/VA2EATs0w+2YhGR+7uWXXVH0tGR29WPioAzXlL0p4CwfisJwIggWxowkm5Pr88Z0ddUIBHnTse73lByF5mzQlWx27HFu72i7vaym06hZH5+4iU34DBBoOewEdC6GewdB04t89/1O/w1cDnyilFU=

公告:
  ver: "2017.10.31"
  內容: |
    <指揮部>
    愛醬更新啦

詞組:
  髒話:
    [
      幹,
      fuck,
      婊子,
      你媽,
      你娘,
      妳媽,
      妳娘,
      操你,
      操妳,
      白癡,
      神經病,
      敗類,
      人渣,
    ]
  自己的: [me, my, myself, 自己, 個人, 我]
  是: ["1", 是, 真, "True", "on", "yes", "y", 打開, 開啟]
  否: ["0", 否, 假, "False", "off", "no", "n", 關閉]
  全部: [all, full, 全部, 所有, 全]

加入好友:
  - |
    只是個做好玩的機器人
    用來群組打圖戰或嘴砲用
    還有一些小功能(慢慢新增)
    詳細輸入【說明】查詢
  - https://i.imgur.com/JIeK6wI.jpg

加入群組:
  - |
    愛醬入侵此群組啦！
    愛醬是
    打嘴砲、圖包、小工具的機器人
    詳細使用輸入【指令】查詢
  - https://i.imgur.com/JIeK6wI.jpg

指令說明: |
  【指令】(本說明)
  【列表=群組/個人】 (預設群組)
  【學習=關鍵字=內容】
  【刪除=關鍵字】
  【設定】 
  【意見=文字】
  【回憶】
  【開車】【查詢】

  關鍵字可用雙米號[**]為任意字
  內容可用雙底線[__]隨機一組
  內容可用雙直槓[||]分段(最多5段)
  內容為圖片網址可以傳圖(jpg png)
  詳細輸入【學習】查詢
  少部分功能在群組跟1對1不同

  ※請不要使用人身攻擊字眼
  ※如產生任何問題
  一律以LINE官方紀錄為準
  ※作者絕對不會儲存你的內容
  但不建議你在需要保密的地方使用
  ※愛醬的好友已滿 請加@foy3843q

學習說明: |
  【學習=關鍵字】
  可查詢關鍵字的內容
  【學習=關鍵字=內容】
  關鍵字可用雙米號[**]為任意字
  內容可用雙底線[__]隨機一組
  內容可用雙直槓[||]分段(最多5段)
  內容為圖片網址可以傳圖(jpg png)
  內容含有雙井號[##A=B]為參數A=B

  隨機模式：
  每段最末尾可用[%]指定比重(默認1)
  例:AAA%10__BB%2__CCC
  出現AAA的機率7/13
  出現BBB的機率2/13
  出現CCC的機率1/13
  選項可用[##種子=N] N為數字(小時)
  例:##種子=24
  同一個人在24小時內隨機的內容會一樣
  ※LINE版本低於7.5.0並沒有同意條款的人 會識別為同一個人
  ※如果要多重觸發關鍵字後面要有【**】
  觸發方法是【關鍵字*數字】
  最大可以20連發
  有設定種子的時候不能使用

搜尋說明: |
  目前支援三種網域
  分別為 動漫花園、nyaa、nyaa2
  命令皆為
  【網域=參數=關鍵字】
  直接輸入網域名稱可以查看細項

#------------------------
#以下是舊的 待調整

回應:
  找不到: https://i.imgur.com/FE6o3xG.jpg

文檔:
  開車: |
    正確姿勢
    【開車=磁力連結】
    【停車】
    (磁力連結可用低調碼)
    (目前只支援BT車 其他以後再說)
    一次申請6個小時 (可能上調)
    由於你知道的理由
    檔案只存於快取中
    某些狀況可能會提前中斷
    檔案暫時限制2G (可能下修)
    ※作者絕對不會儲存你的內容

    (此功能於測試版)
    (有可能提早被中斷)
    1*暫時只支援BT車
    2*有些翻車裝況不會提醒
    3*時間到不會提示 網頁直接失連
    4*此功能很吃資源 隨時可能暫停
    5*如果有建議請使用回報功能
    6*暫時沒有密碼 如果不想讓別人知道
    建議加愛醬好友 1對1使用

  動漫花園: |
    動漫花園 搜尋功能
    【dmhy=參數=關鍵字】
    參數目前只能輸入搜尋數量
    (目前最多5)

    1*暫時不能設定其他值
    2*請不要太過快的連續輸入
    3*暫時只能分開用
    之後會跟開車整合在一起

  nyaa: |
    nyaa 搜尋功能
    【nyaa=參數=關鍵字】
    參數目前只能輸入搜尋數量
    (目前最多5)

    1*請注意簡繁體
    (之後會有自動轉換功能)
    2*暫時不能設定其他值
    3*請不要太過快的連續輸入
    4*暫時只能分開用
    之後會跟開車整合在一起

  nyaa2: |
    sukebei(nyaa裏) 搜尋功能
    【nyaa2=參數=關鍵字】
    參數目前只能輸入搜尋數量
    (目前最多5)

    1*請注意簡繁體
    (之後會有自動轉換功能)
    2*暫時不能設定其他值
    3*請不要太過快的連續輸入
    4*暫時只能分開用
    之後會跟開車整合在一起
